version: '3'

services:
  web:
    build: .
    volumes:
      - .:/code:z
      - db_data:/data
    ports:
      - "3000:3000"
    environment:
      DBUSER: libretube
      DBDATABASE: libretube
      DBPASSWORD: hunter12

volumes:
    db_data:
