version: '3'

services:
  db:
    restart: always
    environment:
      POSTGRES_PASSWORD: hunter12
      POSTGRES_USER: libretube
      POSTGRES_DB: libretube

  web:
    restart: always
    ports:
      - "80:3000"
    environment:
      NODE_ENV: production
      DBHOST: db
      DBUSER: libretube
      DBDATABASE: libretube
      DBPASSWORD: hunter12
