version: '3'

services:
  db:
    image: postgres:10-alpine
    volumes:
      - db_data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: hunter12
      POSTGRES_USER: libretube
      POSTGRES_DB: libretube

  web:
    build: .
    volumes:
      - .:/code:z
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DBHOST: db
      DBUSER: libretube
      DBDATABASE: libretube
      DBPASSWORD: hunter12

volumes:
    db_data:
